### PR TITLE
Added additional hooks and state callbacks

### PR DESCRIPTION
**Pull request by voxxit**
This implementation will:

1. Send a `timer_tick` event on each timer update with:
   - Formatted time string
   - Milliseconds remaining

2. Send `timer_state_changed` events when the timer:
   - Starts
   - Pauses
   - Stops
   - Completes
   
3. Provide a WebSocket request `get_timer_state` to query the current timer state

One can now use these events in OBS WebSocket clients to:

- Display timer updates in chat
- Trigger scene changes based on specific times
- Control other OBS elements based on timer state
- Build external applications that react to the timer (i.e. displaying the countdown on my Stream Deck)

#### Example usage in an OBS WebSocket client:

```javascript
// Example of listening for timer events
obs.on('Ashmanix.CountdownTimer.timer_tick', data => {
    console.log(`Timer: ${data.time_display}`);
});

obs.on('Ashmanix.CountdownTimer.timer_state_changed', data => {
    console.log(`Timer state changed to: ${data.state}`);
});
```

### CODE REVIEW

**Comment by voxxit** [comment]
For what it's worth, I [wrote a test script](https://gist.github.com/voxxit/53d69f1ebcae42d7828242d1f15aa7bd) to ensure the functionality works as intended after building the plugin locally, and it passed muster: 

```
Connecting to OBS...
Successfully connected to OBS
Timer state: {
  requestType: 'get_timer_state',
  responseData: { is_running: false, success: true, time_left_ms: 5400000 },
  vendorName: 'ashmanix-countdown-timer'
}
Timer started
Received vendor event: {
  eventType: 'timer_state_changed',
  eventData: { state: 'started', text_source: 'Text (FreeType 2)' }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:59', time_left_ms: 5399000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:58', time_left_ms: 5398000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:57', time_left_ms: 5397000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:56', time_left_ms: 5396000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:55', time_left_ms: 5395000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:54', time_left_ms: 5394000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:53', time_left_ms: 5393000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:52', time_left_ms: 5392000 }
}
Received vendor event: {
  eventType: 'timer_tick',
  eventData: { time_display: '01:29:51', time_left_ms: 5391000 }
}
Disconnected from OBS
```

**Comment by ashmanix** [comment]
Hi, Thanks for the PR this looks good but there is one error coming up when running compilation. Can you check in `countdown-widget.cpp` where you have created the new callback function you aren't using `request_data` so you need to add a line in the function `UNUSED_PARAMETER(request_data);` otherwise the checks will fail. You an refer to line 268 where I have done this.

If you can make this change and I'll rerun the checks and if they pass this will be good to go. Thanks again!

**Review by ashmanix — CHANGES_REQUESTED** [review]
Hi, Thanks for the PR this looks good but there is one error coming up when running compilation. Can you check in countdown-widget.cpp where you have created the new callback function you aren't using request_data so you need to add a line in the function UNUSED_PARAMETER(request_data); otherwise the checks will fail. You an refer to line 268 where I have done this.

If you can make this change and I'll rerun the checks and if they pass this will be good to go. Thanks again!

**Comment by voxxit** [comment]
@ashmanix All good! I had already made that fix, but forgot to push it up. Thanks!

**Review by ashmanix — APPROVED** [review]

**Pull request merged**
